import { createPinia, defineStore } from 'pinia';

export const pinia = createPinia();

export const useStore = defineStore({
  id: 'store',
  state: () => ({
    cases: [
      {
        id: 1,
        title: 'Workhub office Webflow Webflow Design',
        image: '/public/home-portfolio-project-1.jpg',
        description: 'Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam',
        singleDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.',
        category: 'Webflow Design',
        client: 'Facebook',
        service: 'Product Design',
        deliverable: 'UI Screens, UX Flow & Prototype',
        heading2: 'About the project',
        paragraph2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        heading3: 'How we do it',
        paragraph3: 'Labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lists: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit', 'Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea', 'Duis aute irure dolor in reprehenderit in voluptate velit esse', 'Excepteur sint occaecat cupidatat non proident, sunt in culpa'],
      },
      {
        id: 2,
        title: 'Unisaas Website Design',
        image: '/public/home-portfolio-project-2.jpg',
        description: 'Euismod faucibus turpis eu pellentesque et velit.',
        category: 'UI Design',
      },
      {
        id: 3,
        title: 'Worship Website Design',
        image: '/public/home-portfolio-project-3.jpg',
        description: 'Euismod faucibus turpis gravida.',
        category: 'UI Design',
      },
      {
        id: 4,
        title: 'Template 4',
        image: '/public/home-portfolio-project-4.jpg',
        description: 'Euismod faucibus turpis gravida.',
        category: 'Figma Design',
      },
      {
        id: 5,
        title: 'Template 5',
        image: '/public/home-portfolio-project-5.jpg',
        description: 'Euismod faucibus turpis eu gravida mi. Pellentesque et velit aliquam',
        category: 'Webflow Design',
      },
      {
        id: 6,
        title: 'Template 6',
        image: '/public/home-portfolio-project-6.jpg',
        description: 'Euismod faucibus turpis eu pellentesque et velit.',
        category: 'UI Design',
      },
      {
        id: 7,
        title: 'Template 7',
        image: '/public/home-portfolio-project-7.jpg',
        description: 'Euismod faucibus turpis gravida.',
        category: 'UI Design',
      },
      {
        id: 8,
        title: 'Template 8',
        image: '/public/home-portfolio-project-8.jpg',
        description: 'Euismod faucibus turpis gravida.',
        category: 'Figma Design',
      },
      {
        id: 9,
        title: 'Template 9',
        image: '/public/home-portfolio-project-9.jpg',
        description: 'Euismod faucibus turpis gravida.',
        category: 'Figma Design',
      },
    ],
    blog: [
      {
        id: 1,
        date: '27 Jan 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-1.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 2,
        date: '28 Jan 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-2.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 3,
        date: '29 Jan 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-3.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 4,
        date: '3 Feb 2022',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-4.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 5,
        date: '6 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-5.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 6,
        date: '11 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-6.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 7,
        date: '14 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-7.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 8,
        date: '17 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-8.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 9,
        date: '21 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-9.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
      {
        id: 10,
        date: '23 Feb 2021',
        title: 'How one Webflow user grew his single person consultancy from $0-100K in 14 months',
        image: '/public/single-blog/single-10.jpg',
        description: 'See how pivoting to Webflow changed one person’s sales strategy and allowed him to attract',
      },
    ],
    teamMembers: [
      {
        id: 1,
        name: 'John Smith',
        position: 'CEO',
        photo: 'john-smith.jpg',
      },
      {
        id: 2,
        name: 'Simon Adams',
        position: 'CTO',
        photo: 'simon-adams.jpg',
      },
      {
        id: 3,
        name: 'Paul Jones',
        position: 'Design Lead',
        photo: 'paul-jones.jpg',
      },
      {
        id: 4,
        name: 'Sara Hardin',
        position: 'Project Manager',
        photo: 'sara-hardin.jpg',
      },
    ],
    tariffs: [
      {
        price: '$299',
        per: 'Per Design',
        title: 'Landing Page ',
        description: 'When you’re ready to go beyond prototyping in Figma, ',
        points: [
          { text: 'All limited links', included: true },
          { text: 'Own analytics platform', included: true },
          { text: 'Chat support', included: true },
          { text: 'Optimize hashtags', included: false },
          { text: 'Unlimited users', included: false },
        ],
      },
      {
        price: '$399',
        per: 'Multi Design',
        title: 'Website Page',
        description: 'When you’re ready to go beyond prototyping in Figma, Webflow’s ready to help.',
        points: [
          { text: 'All limited links', included: true },
          { text: 'Own analytics platform', included: true },
          { text: 'Chat support', included: true },
          { text: 'Optimize hashtags', included: true },
          { text: 'Unlimited users', included: true },
        ],
      },
      {
        price: '$499 +',
        per: 'Per Design',
        title: 'Complex Project',
        description: 'When you’re ready to go beyond prototyping in Figma',
        points: [
          { text: 'All limited links', included: true },
          { text: 'Own analytics platform', included: true },
          { text: 'Chat support', included: true },
          { text: 'Optimize hashtags', included: true },
          { text: 'Unlimited users', included: true },
          { text: 'Assist and Help', included: true },
        ],
      },
    ],
  }),
});